name: Generate High Aesthetic Cards

on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Stats Cards
        uses: teoxoy/profile-readme-stats@v1
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          include_all_commits: true
          # 使用你喜欢的 radical 主题
          theme: radical
      - name: Commit & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add *.svg
          git commit -m "Update high-aesthetic stats cards with private data" || exit 0
          git push
